import csv
import pandas as pd
df = pd.read_csv("Data/originalShotData.csv")
with open("Data/originalShotData.csv") as csv_file:
	csv_reader = csv.reader(csv_file)
	i=0
	typeToIndex, indexToType = {}, {}
	pointsPer = {}
	realPointsPer = {}
	# This creates maps to store the data to indices and vice versa
	for line in csv_reader:
		for dataType in line:
			typeToIndex[dataType] = i
			indexToType[i] = dataType
			i+=1
		break
	i=0
	points = {}
	# This loop fills pointPer, where key is (x,y) and the value is a tuple where 1st value is the total points scored from that position, and 2nd value is number of shots from that position
	for line in csv_reader:
		x = int(line[typeToIndex['X Location']])
		y = int(line[typeToIndex['Y Location']])
		if((x, y) not in pointsPer):
			pointsPer[(x, y)] = (0, 0)
		pointsPer[(x, y)] = (pointsPer[(x,y)][0]+int(line[typeToIndex['Shot Made Flag']]) * int(line[typeToIndex['Shot Type']][0]), pointsPer[(x, y)][1] + 1)
	directions = [[1,0], [-1, 0], [0, 1], [0, -1], [1, 1], [1, -1],[-1, 1],[-1, -1]]
	# This calculates the average point generated by a shot from that position and all of its neighbours
	for key in pointsPer:
		points = pointsPer[key][0]
		shots = pointsPer[key][1]
		for x,y in directions:
			newCoords = (key[0] + x, key[1] + y)
			if(newCoords in pointsPer):
				points += pointsPer[newCoords][0]
				shots += pointsPer[newCoords][0]
		realPointsPer[key] = points / shots
	newCol = []
with open("Data/originalShotData.csv") as csv_file:
	csv_reader = csv.reader(csv_file)
	# Creates a new csv with a newCol for points per possesion(calculated above)
	for line in csv_reader:
		if((line[typeToIndex['X Location']].startswith('-') and line[typeToIndex['X Location']][1:].isdigit()) or (line[typeToIndex['X Location']].isdigit())):
			newCol.append(realPointsPer[(int(line[typeToIndex['X Location']]),int(line[typeToIndex['Y Location']]))])
df["Points Per Possesion"] = newCol
df.to_csv('Data/newShotData.csv')
